/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClientDetails: typeof import('./src/components/ClientDetails.vue')['default']
    ClientTimeline: typeof import('./src/components/ClientTimeline.vue')['default']
    ContractCard: typeof import('./src/components/ContractCard.vue')['default']
    ContractDetails: typeof import('./src/components/ContractDetails.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineFilter: typeof import('./src/components/TimelineFilter.vue')['default']
  }
}
